plugins {
    id 'java'
    id 'net.neoforged.moddev' version '1.0.21'
}

version = '0.1.0'
group = 'dev.nwillis.paperclip'
base.archivesName = 'paperclip'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven { url = 'https://maven.squiddev.cc' }
}

neoForge {
    version = '21.1.95'

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        paperclip {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation 'cc.tweaked:cc-tweaked-1.21.1-forge:1.120.0'
}
