-- BASEWALK level 'survey_campus' - generated by tools/scan2map.lua from a survey scan
return {
  w = 37, l = 37,
  spawn = { x = 0, z = 0 },
  cells = ".................p....................................p.p..................................pBPPPPPPPPPPPPPPPPPB.................pP..SX.ppppVV.R....P.................pP..pppp..p...R....P.................pPSSpC.CCpM........P.................pPSp.C...ppppX.....P.................pppp.ppppp.........P.....................p..............P.....................pp.............P..................PS..p#............P..................P.................P..................P.................P..................P.....TTTT........P..................BPPPPPPPPPPPPPPPPPB...................................................................................................................BPP...PPB............................P.......P............................P.......P............................P.......P............................P.......P............................P.......P............................P.......P............................PMNNNN..P............................BPPPPPPPB..........................................................................................................................................................................................................................................................................................................................................................................................................",
  legend = {
    ["S"] = { name = "sophisticatedstorage:barrel", color = "brown" },
    ["T"] = { name = "apotheosis:gem_cutting_table", color = "red" },
    ["R"] = { name = "minecraft:white_bed", color = "pink" },
    ["P"] = { name = "minecraft:purple_concrete", color = "purple" },
    ["M"] = { name = "computercraft:disk_drive", color = "magenta" },
    ["N"] = { name = "computercraft:monitor_advanced", color = "lime" },
    ["#"] = { name = "sophisticatedbackpacks:diamond_backpack", color = "white" },
    ["C"] = { name = "sophisticatedstorage:netherite_chest", color = "orange" },
    ["p"] = { name = "pipez:fluid_pipe", color = "cyan" },
    ["X"] = { name = "trashcans:item_trash_can", color = "lightGray" },
    ["B"] = { name = "minecraft:polished_blackstone", color = "gray" },
    ["V"] = { name = "easy_villagers:auto_trader", color = "yellow" },
  },
}
