-- scan2map: compiles a survey scan into a BASEWALK level - the base
-- itself, as a raycastable map. Takes the eye-level slice (y=1) with a
-- ground-slice (y=0) fallback for low furniture, assigns each block
-- family a wall color, and emits a compact loadable map module.
--
--   lua54 tools/scan2map.lua <scan.json> <out.lua> [--eye 1]
--
-- Map module: { w, l, cells = <w*l string>, legend = {char->{name,color}},
--   spawn = {x, z} }  where cells is row-major (z*w+x+1), "." = open.
local M = {}

-- block family -> map char + CC color name (basewalk maps to colors.*)
local FAMILIES = {
  { find = "purple_concrete", char = "P", color = "purple" },
  { find = "blackstone", char = "B", color = "gray" },
  { find = "glass", char = "G", color = "lightBlue" },
  { find = "barrel", char = "S", color = "brown" },
  { find = "chest", char = "C", color = "orange" },
  { find = "water", char = "W", color = "blue" },
  { find = "farmland", char = "F", color = "green" },
  { find = "pipe", char = "p", color = "cyan" },
  { find = "cable", char = "p", color = "cyan" },
  { find = "table", char = "T", color = "red" },
  { find = "controller", char = "M", color = "magenta" },
  { find = "condenser", char = "M", color = "magenta" },
  { find = "drive", char = "M", color = "magenta" },
  { find = "computer", char = "N", color = "lime" },
  { find = "monitor", char = "N", color = "lime" },
  { find = "bed", char = "R", color = "pink" },
  { find = "trader", char = "V", color = "yellow" },
  { find = "trash", char = "X", color = "lightGray" },
}
local DEFAULT = { char = "#", color = "white" }

function M.family(name)
  for _, f in ipairs(FAMILIES) do
    if name:find(f.find, 1, true) then return f end
  end
  return DEFAULT
end

-- minimal JSON for the survey shape (objects/arrays/strings/ints)
function M.parseJson(text)
  local pos = 1
  local function skip()
    while true do
      local c = text:sub(pos, pos)
      if c == " " or c == "\n" or c == "\r" or c == "\t" then pos = pos + 1
      else return end
    end
  end
  local parse
  local function parseString()
    pos = pos + 1
    local out = {}
    while true do
      local c = text:sub(pos, pos)
      if c == '"' then pos = pos + 1 return table.concat(out) end
      if c == "\\" then
        pos = pos + 1
        out[#out + 1] = text:sub(pos, pos)
      else
        out[#out + 1] = c
      end
      pos = pos + 1
    end
  end
  local function parseNumber()
    local s = pos
    if text:sub(pos, pos) == "-" then pos = pos + 1 end
    while text:sub(pos, pos):match("%d") do pos = pos + 1 end
    return tonumber(text:sub(s, pos - 1))
  end
  parse = function()
    skip()
    local c = text:sub(pos, pos)
    if c == "{" then
      pos = pos + 1
      local obj = {}
      skip()
      if text:sub(pos, pos) == "}" then pos = pos + 1 return obj end
      while true do
        skip()
        local key = parseString()
        skip()
        pos = pos + 1   -- ':'
        obj[key] = parse()
        skip()
        local d = text:sub(pos, pos)
        pos = pos + 1
        if d == "}" then return obj end
      end
    elseif c == "[" then
      pos = pos + 1
      local arr = {}
      skip()
      if text:sub(pos, pos) == "]" then pos = pos + 1 return arr end
      while true do
        arr[#arr + 1] = parse()
        skip()
        local d = text:sub(pos, pos)
        pos = pos + 1
        if d == "]" then return arr end
      end
    elseif c == '"' then
      return parseString()
    else
      return parseNumber()
    end
  end
  return parse()
end

-- scan -> map: solid at eye level wins; else low furniture at ground
-- level also blocks (chests, tables); air/unknown = open
function M.compile(scan, eyeY)
  eyeY = eyeY or 1
  local w, l = scan.w, scan.l
  local eye = scan.layers[eyeY + 1]
  local ground = scan.layers[1]
  local cells = {}
  local legend = {}
  local spawn = nil
  for z = 0, l - 1 do
    for x = 0, w - 1 do
      local i = z * w + x + 1
      local v = eye and eye[i] or 0
      if (not v or v <= 0) and ground then
        v = ground[i]
      end
      if v and v > 0 then
        local fam = M.family(scan.palette[v])
        cells[i] = fam.char
        legend[fam.char] = { name = scan.palette[v], color = fam.color }
      else
        cells[i] = "."
        if not spawn and (v == 0 or v == nil or v <= 0) then
          spawn = { x = x, z = z }
        end
      end
    end
  end
  return { w = w, l = l, cells = table.concat(cells),
    legend = legend, spawn = spawn or { x = 0, z = 0 } }
end

function M.emit(map, label)
  local out = {}
  out[#out + 1] = "-- BASEWALK level '" .. (label or "base")
    .. "' - generated by tools/scan2map.lua from a survey scan"
  out[#out + 1] = "return {"
  out[#out + 1] = ("  w = %d, l = %d,"):format(map.w, map.l)
  out[#out + 1] = ("  spawn = { x = %d, z = %d },"):format(map.spawn.x, map.spawn.z)
  out[#out + 1] = '  cells = "' .. map.cells .. '",'
  out[#out + 1] = "  legend = {"
  for char, e in pairs(map.legend) do
    out[#out + 1] = ('    ["%s"] = { name = "%s", color = "%s" },')
      :format(char, e.name, e.color)
  end
  out[#out + 1] = "  },"
  out[#out + 1] = "}"
  return table.concat(out, "\n") .. "\n"
end

if _TEST then return M end

local args = { ... }
if #args < 2 then
  print("usage: lua54 tools/scan2map.lua <scan.json> <out.lua> [--eye N]")
  os.exit(1)
end
local eyeY = 1
for i = 3, #args do
  if args[i] == "--eye" then eyeY = tonumber(args[i + 1]) or 1 end
end
local f = assert(io.open(args[1], "r"))
local scan = M.parseJson(f:read("*a"))
f:close()
local map = M.compile(scan, eyeY)
local open = 0
for i = 1, #map.cells do
  if map.cells:sub(i, i) == "." then open = open + 1 end
end
local out = assert(io.open(args[2], "w"))
out:write(M.emit(map, args[1]:match("([^/\\]+)%.json$")))
out:close()
print(("map %dx%d: %d open cells, spawn %d,%d -> %s")
  :format(map.w, map.l, open, map.spawn.x, map.spawn.z, args[2]))
